FROM eclipse-temurin:8-focal

WORKDIR /app

# To build a native image for ARMv8 we can use the existing
# image and pull the files out of it. The saves us from running
# sbt images in emulation mode (which will not complete)
COPY --from=rutkai/vindinium /app /app
RUN chown -R www-data: /app

EXPOSE 9000
USER www-data

CMD ["bin/vindinium"]
