version: "3.8"

services:
  vindinium:
    build:
      context: .
    container_name: vindinium
    depends_on:
      - mongodb
    ports:
      - "9000:9000"
    restart: unless-stopped
  mongodb:
    # MongoDB v4 + v5 do not support Raspbery Pi 4 CPU for ARMv8
    # MongoDB v4 works well enough under emulation but v5 does not
    image: mongo:4.4
    platform: linux/amd64
    container_name: vindinium-mongodb
    volumes:
      - ./var/db/:/data/db
    restart: unless-stopped
